### ISSUE TITLE
Error when trying to copy paste an image

### ISSUE THREAD

**Issue by dawitts** [ssricardo/anki-web-browser#8] opened 2021-06-07 07:11 UTC
when ever am trying to copy an image from google image it send this message. It works fine on other website like wikipedia
![image](https://user-images.githubusercontent.com/85479065/120974159-78b40a00-c778-11eb-9da2-44296a6f26b0.png)
what shall i do bro.
I use linux anki on my chromebook.

**Comment by ssricardo** [comment] 2021-06-14 10:06
Hi @dawitts .

Actually those images unfortunately won't work.
The add-on underneath uses Anki platform functionalities, including the part for downloading images. 
So the add-on work only for same images as when you paste a link on Anki (namely URLs with the suffix mentioned on the message). 

This limitation is actually already on the documentation (https://github.com/ssricardo/anki-web-browser#limitation).

As it's not a bug and there's nothing I can do here, I'm closing the issue, ok?!

**Closed by ssricardo** 2021-06-14 10:06 UTC
